### ISSUE TITLE
ghdl/synth:beta image a691ca20ad4b broken

### ISSUE THREAD

**Issue by mikey** [ghdl/docker#29] opened 2020-07-01 06:02 UTC
The latest image a691ca20ad4b on docker.io is broken with this:

```
******************** GHDL Bug occurred ***************************
Please report this bug on https://github.com/ghdl/ghdl/issues
GHDL release: 1.0-dev (v0.37.0-794-ge854f72b@buster-mcode) [Dunoon edition]
Compiled with unknown compiler version
Target: x86_64-linux-gnu
/src/
Command line:

Exception SYSTEM.ASSERTIONS.ASSERT_FAILURE raised
Exception information:
raised SYSTEM.ASSERTIONS.ASSERT_FAILURE : vhdl-annotations.adb:1401
******************************************************************
ERROR: vhdl import failed.

```

The last revision I tried cb1eeee4ff96 worked fine.

**Comment by mikey** [comment] 2020-07-01 06:18
This started falling over for my microwatt testing @eine 
https://github.com/mikey/microwatt/runs/825305578?check_suite_focus=true

**Comment by mikey** [comment] 2020-07-01 06:48
the above are the SHAs I get with podman. with docker
works:
sha256:6d75dbcdbc5b7df2f1a5662012db98c5c5a94cb5b4e9fca14334b6214cf0ab84 
broken:
sha256:bb21846ecb77497b1be2b486924d6de6eb7ff39537e3562d24bb8032bf9ea47a

**Comment by tgingold** [comment] 2020-07-01 16:16
I can reproduce the crash, I am investigating.

**Comment by eine** [comment] 2020-07-01 21:22
@mikey, all images were regenerated automatically a couple of hours ago (when Tristan pushed to ghdl/ghdl). Hence, if that was the issue, it should be fixed. If so, please do close this issue. Otherwise, let us know ;)

And thanks for reporting!

**Comment by mikey** [comment] 2020-07-01 23:10
Something else seems very unhappy now with the images
https://github.com/mikey/microwatt/runs/828420039?check_suite_focus=true

```e292e096e664: Pull complete
Digest: sha256:09b82f36e828263326227d80832facbfc75e3139cbfc33c5acad7e49bef4cc9b
Status: Downloaded newer image for ghdl/synth:beta
docker: Error response from daemon: OCI runtime create failed: container_linux.go:349: starting container process caused "exec: \"-m\": executable file not found in $PATH": unknown.
make: *** [microwatt.v] Error 127
Makefile:188: recipe for target 'microwatt.v' failed```

**Comment by eine** [comment] 2020-07-02 00:42
I think that `yosys` is missing. It should be the first arg (after the image name and before `-m`): https://github.com/mikey/microwatt/runs/828420039?check_suite_focus=true#step:3:4 Compare with https://github.com/mikey/microwatt/runs/825480569?check_suite_focus=true#step:3:4

So, add `yosys` at the end of https://github.com/mikey/microwatt/blame/8036b7458cb7a74f19e497d24858a9849d010f7b/Makefile#L33

**Comment by mikey** [comment] 2020-07-02 01:02
@eine yes my screwup. Sorry.

**Comment by eine** [comment] 2020-07-02 01:59
No worries. I'm closing this, since it seems to be working: https://github.com/mikey/microwatt/actions/runs/154770099

**Closed by eine** 2020-07-02 01:59 UTC

**Comment by mikey** [comment] 2020-07-02 02:40
FWIW passing now. Thanks
